---

- hosts: '{{target}}'
  remote_user: vagrant
  connection: local
  gather_facts: no

  vars_files:
  - ../defaults/main.yml

  tasks:
  - name: Configuring selected Core Router as Mapping Server
    iosxr_config:
      provider:
        host: "{{ ansible_host }}"
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'
      src: ../templates/mapping-server.j2
      backup: yes
