---

- hosts: '{{target}}'
  remote_user: vagrant
  connection: local
  gather_facts: no

  vars_files:
  - ../defaults/main.yml

  tasks:
  - name: Configuring SR for global internet services
    iosxr_config:
      provider:
        host: "{{ ansible_host }}"
        username: '{{ ansible_ssh_user }}'
        password: '{{ ansible_ssh_pass }}'
      src: ../templates/Global-internet-loopback-template.j2
      backup: yes
